alias ws='cd /var/www'
alias g='geany'
alias desk='cd ~/Desktop'
alias f='uptime ; echo ; free -m ; echo ; df -Th'
alias wget='wget -c -T5'
alias cd..="cd .."
alias s="sublime_text"
alias dig='dig +nostats +nocomments +nocmd'
alias j='jobs'
