alias ws='cd /var/www'
alias g='geany'
alias desk='cd ~/Desktop'
alias f='free -m'
alias wget='wget -c -T5'
alias cd..="cd .."
alias s="sublime_text"
alias dig='dig +nostats +nocomments +nocmd'
alias j='jobs'
