alias g='git'
alias gg='git status'
alias ggs='git status -s'
alias gco='git checkout'
alias gc='git commit -m'
alias ga='git add'
alias gb='git branch'
alias gcb='git checkout -b'
alias gl='git log'
alias gp='git pull'
alias glog="git log --all --decorate=short --abbrev-commit --date=relative \
  --pretty=format:'%C(bold red)%<(7,trunc) %h%Creset │ %C(green)%<(14,trunc)%cr%Creset │ %C(blue)%<(16,trunc)%an%Creset │ %C(magenta)%<(26,trunc)%ae%Creset │ %C(white)%s%Creset %C(dim yellow)%d%Creset'"
alias gcm='git checkout main'
alias gcd='git checkout develop'
alias gbb='git bisect bad'
alias gbg='git bisect good'
alias gd='git diff --color | diff-so-fancy'
alias shortlog='git shortlog -n -s'
