alias g='git'
alias gg='git status'
alias ggs='git status -s'
alias gco='git checkout'
alias gc='git commit -m'
alias ga='git add'
alias gb='git branch'
alias gcb='git checkout -b'
alias gl='git log'
alias gp='git pull'
alias glog="git log \
    --graph --pretty=format:'%Cred%h%Creset \
    -%C(yellow)%d%Creset %s %Cgreen(%cr) \
    %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gcm='git checkout main'
alias gcd='git checkout develop'
alias gbb='git bisect bad'
alias gbg='git bisect good'
alias gd='git diff --color | diff-so-fancy'
alias shortlog='git shortlog -n -s'
