[Sizes]
SplitterPos=200
WindowSize=@Size(1335 971)

[View]
BigIconSize=48
Mode=Thumbnail
ScrollPerPixel=true
ShowHidden=false
ShowThumbnails=true
SmallIconSize=24
SortColumn=mtime
SortFolderFirst=true
SortOrder=ascending
ThumbnailIconSize=128
