[General]
__userfile__=true
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessWatcher=true
enableLidWatcher=true
iconType=4
lidClosedAcAction=-1
lidClosedAction=-1
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
powerLowAction=6
powerLowLevel=20
powerLowWarning=240
runCheckLevel=1
showIcon=true
useThemeIcons=true
